### ISSUE TITLE
Hide toolbar navigation item when djvu has only one page?

### ISSUE THREAD

**Issue by ghost** [mateusz-matela/djvu-html5#10]
Perhaps, the toolbar navigation item should be hidden when the djvu has only one page?

**Comment by mateusz-matela** [comment]
Interesting idea, but I'm not convinced.
Is it about saving space? It doesn't take that much (ok, maybe on mobile) and it's supposed to hide anyway when the mouse movement stops.
And I've never seen an app's GUI changing like that, it can be confusing to some users. "Page selection didn't appear and I can't scroll to the next page - is this thing broken?" There's no such problem when page selection drop-down shows only one item.

**Comment by ghost** [comment]
Maybe you are correct, but I think some users might see navigation arrows, click on them, and get confused.  It's true that the drop-down shows only one item, but there are still arrows.  Maybe, in this case, instead of arrows and a drop-down, just overlay the text "1/1" to prevent any confusion?  It's a very minor point, anyway.

**Comment by mateusz-matela** [comment]
The latest version disables and greyouts buttons if clicking them would not have effect. Should be enough to avoid any confusion.
