### ISSUE TITLE
Is OCR planned for HTML5 plugin?

### ISSUE THREAD

**Issue by Ulvarin** [mateusz-matela/djvu-html5#9]
Hello, same question as in the subject.
Will HTML5 support the OCR in future?

Witam,
Wtyczka jest genialna i świetnie działa, umożliwiając ludziom mobilne przeglądanie treści, tylko brakuje w niej bardzo możliwości przeszukiwania tekstu przez OCR. Czy jest w planach wprowadzenie tego bądź jakieś inne rozwiązanie to umożliwiające?

**Comment by mateusz-matela** [comment]
OCR musi być wykonane nie przez przeglądarkę, tylko przez twórcę dokumentu DjVu. Jeśli w DjVu jest dodana warstwa tekstowa, to aplikacja pozwala go przeszukiwać oraz kopiować. Zostało to dodane w ostatniej wersji (w listpadzie) i działa na takiej zasadzie, że na wyrenderowanym dokumencie DjVu nałożona jest przezroczysta warstwa z dokumentem HTML - dzięki temu tekst można zaznaczać i przeszukiwać jak na każdej innej stronie (zwykle Ctrl+F). Można to przetestować na demo: http://mateusz-matela.github.io/djvu-html5/demo.html

**Comment by Ulvarin** [comment]
Witam,,
Pisze tutaj w trochę innej sprawie niż powyższy temat.
Jako, że przeglądarki już bardzo niedługo zamierzają całkowicie porzucić 
większość wtyczek (ff,chrome),
wiadomo coś Panu może na temat publikacji zabezpieczonych a HTML5?
Aktualnie jesteśmy już na najnowszym pluginie HTML5 i wszystko ślicznie 
działa, w przypadku publikacji zabezpieczonych wciąż używamy djvu + 
32bit przeglądarek (na x64 już nie działa djvu).
W najbliższym czasie nawet to stanie się niemożliwe, bądź wymusi brak 
aktualizacji przeglądarek w celu kompatybilności - co jest ew. 
rozwiązaniem tymczasowym ale nie stałym.

Pozdrawiam,
Marek Semeniuk

**Comment by mateusz-matela** [comment]
Witam, obsługa zabezpieczonych publikacji w tej aplikacji jest możliwa, ale nie prosta do zrobienia. Myślę, że w ciągu 2-3 miesięcy znajdę czas na wgryzienie się w ten temat.

**Comment by Ulvarin** [comment]
Rozumiem, dziękuję za odpowiedź.
Mam jeszcze jedno pytanie związane z  .pdf w dlibra.
Dziś np mozilla dostała update (koniec wtyczek) i jak djvu na html5 działa
super to pdf wywala na ekran wyboru wtyczki (bo brak wtyczek), mobilne
chrome robi już tez to samo, nawet opera w końcu to zrobi bo silnik
chrome.  Po ustawieniu bezpośrednio na przeglądarkę ręcznie pdf oczywiście
działa. Czy zmieniając analogicznie jak przy auto html5 w webapps tylko
wtyczce pdf browser.override wartość na przeciwna sprawi to automatyczne
ustawienie pdf każdego bezpośrednio na przeglądarkę a nie poprzez wtyczkę?


08.03.2017 10:01 PM "mateusz-matela" <notifications@github.com> napisał(a):

**Comment by mateusz-matela** [comment]
Nie jestem pewien, najlepiej poeksperymentować. Być moze zupełne usunięcie WEB-INF/formats katalogów związanych z pdf przyniesie oczekiwany efekt.

**Comment by Ulvarin** [comment]
Rozumiem, będę rano kombinować w pracy.
Dziękuję bardzo za pomoc no i za wtyczkę html5  oczywiście. Bez tego dlibra
była nieuzywalna dla przeciętnych użytkowników przez skomplikowanie
konfiguracji pomijając już nawet porzucenie wtyczek wymuszone teraz.
Ogólnie gdyby nie Pana praca dlibra by leżała bezużyteczna poza
hermetycznym prekonfigurowanym środowiskiem bibliotecznym :).

Pozdrawiam
Marek Semeniuk



08.03.2017 10:24 PM "mateusz-matela" <notifications@github.com> napisał(a):

Nie jestem pewien, najlepiej poeksperymentować. Być moze zupełne usunięcie
WEB-INF/formats katalogów związanych z pdf przyniesie oczekiwany efekt.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mateusz-matela/djvu-html5/issues/9#issuecomment-285173891>,
or mute the thread

**Comment by Ulvarin** [comment]
Dzień Dobry,
     W związku z problemami, których  wciąż doświadczają partnerzy LBW, 
chciałem zadać kilka pytań dotyczących dlibra5 jak i 6.

Dlibra 5:
     - Istniejąca wtyczka HTML5 
(https://github.com/mateusz-matela/djvu-html5) wciąż nie obsługuje 
dokumentów zabezpieczonych. W związku z tym mamy pytanie kiedy jest 
planowana jej aktualizacja udostępniająca taką opcję.
W chwili obecnej dlibra5 nie pozwala na wywiązanie się z umowy pomiędzy 
podmiotami a autorami w kwestii zabezpieczeń publikacji.

     - Ten sam problem dotyczy wtyczki .pdf która nie działa na 
przeglądarce mozilla firefox, problem rozwiązuje jej usunięcie 
(bezpośrednie wysyłanie .pdf na przeglądarkę z pominięciem wtyczki)  
jednak stwarza kolejny; obsługę dokumentów zabezpieczonych - czyli jej brak.
Nie istnieje możliwość blokady "łatwego pobierania" publikacji.

Dlibra6:
     - W związku ze zbliżającymi się aktualizacjami do dlibra6 jak i 
chęcią kupna programu przez 2 partnerów chciałem zapytać jak dlibra6 
obsługuje pliki typu .djvu jak i publikacje zabezpieczone (ip/logowanie).
Czy zostały rozwiązane problemy podane w powyżej podanych przykładach 
dlibra5?


     Proszę o podanie rozwiązania pozwalającego na obsługę publikacji 
zwykłych jak i zabezpieczonych godnego naszych czasów ( czyli 
działającego na chrome/FF/opera bez instalacji wtyczek - co jest na nich 
niemożliwe).
Internet explorer + http://www.djvu.com.pl/download.php nie jest 
rozwiązaniem pozwalającym na jakikolwiek bezproblemowy dostęp do 
publikacji przez czytelników.
W obecnej sytuacji korzystanie z systemu jest wciąż niesamowicie 
utrudnione i nie pozwala na pełne korzystanie z systemu przez odbiorców.

Problemy te wciąż istnieją na forach fbc na większość podobnych nie ma 
udzielonych jasnych bądź żadnych odpowiedzi.
http://fbc.pionier.net.pl/qa/index.php/878/czytelnikom-przegl%C4%85danie-instalacji-dodatkowego-oprogramowania
http://fbc.pionier.net.pl/qa/index.php/71/dlaczego-mo%C5%BCna-skopiowa%C4%87-zabezpieczon%C4%85-publikacj%C4%99-pdf
http://fbc.pionier.net.pl/qa/index.php/1122/publikacje-zabezpieczone-djvu-w-dlibrze
http://fbc.pionier.net.pl/qa/index.php/718/chrome-i-wy%C5%9Bwietlanie-publikacji-w-formacie-djvu

Pozdrawiam,

Marek Semeniuk
/Informatyk
"Lubelskiej Biblioteki Wirtualnej"/

**Comment by mateusz-matela** [comment]
Dobry wieczór,

Co do wsparcia zabezpieczonych DjVu w viewerze html5 - jakoś nie mogę przeforsować w zespole, żebyśmy poświęcili na to czas. Może gdyby znalazła się instytucja skłonna zamówić taką funkcję i za nią zapłacić, sprawa posunęłaby się do przodu.

Na zabezpieczanie PDF nie widzę obecnie sensownego technicznie rozwiązania, jako że przeglądarki wyparły Acrobat Readera na rzecz własnych rozwiązań, które po prostu nie respektują stosowanych wcześniej mechanizmów zabezpieczania. Pewnie twórcy doszli do wniosku, że nie ma sensu utrzymywać zabezpieczeń, które niemal każdy odpowiednio zmotywowany użytkownik z dostępem do Google będzie w stanie szybko złamać.

Chyba jedynym wyjściem byłoby znalezienie projektu implementującego przeglądarkę PDF w html5 i zmodyfikowanie go, żeby w odpowiedni sposób pobierał pliki z dLibry i uniemożliwiał kopiowanie treści. Ale to jeszcze więcej pracy niż z DjVu, bo tu przynajmniej jest gotowy projekt, który umiemy modyfikować...
